### ISSUE TITLE
Allow AxisArrays that are missing dimensions and/or names?

### ISSUE THREAD

**Issue by tshort** [mbauman/AxisArrays.jl#1]
I'm still just reading the code (and getting a better feel for staged functions!). On @mbauman's question in the code on allowing missing names, I think we should make axes names mandatory or give defaults. However, we should allow the user to leave out the axes (default to nothing for each). A user might only want the Axis() indexing capability. If folks agree, it would be good to flip the order on the following constructor as follows:
```julia
stagedfunction AxisArray{T,N}(A::AbstractArray{T,N}, names::(Symbol...), axes::(AbstractVector...))
```
Then we need defaults of nothing for each `axes`. Can you have a staged function with default arguments?

**Comment by mbauman** [comment]
Yup, I agree.  We can make the constructors fancier.  Axes and their names are different enough that we should be able to support all flavors here.  If they're axis names are omitted, I currently give them row/col/page defaults.

I think it's most sensible to allow shorter axes and axesnames than the dimensionality of the array.  If you want to name some intermediate dimension, you gotta name all of the ones to its left, too.  Same with the axes.
