### ISSUE TITLE
cat operations

### ISSUE THREAD

**Issue by GordStephen** [mbauman/AxisArrays.jl#25]
It would be great to have AxisArray-specific concatenation operations - it would seem fairly straightforward to implement for concatenating on existing dimensions, but operating on higher (not-yet-existing) dimensions might need a bit more consideration regarding how to create the new axes. Or maybe one would just be required to supply an appropriate `Axis`?

**Comment by mbauman** [comment]
Makes sense.  Concatenating existing axes can also check to make sure that the axes are consistent, which I think is very nice feature, too.

I'm not sure how you'd specify a new dimension's axis, but the default constructor simply uses `row`/`col`/`page`/`dim_N`… as axis names if they're omitted. See `_defaultdimname`. That could work for now.

**Comment by GordStephen** [comment]
Good idea to just use the existing default axis generation. I'll see if I can get some work on this done next week.

Concatenating range-labelled axes might be tricky... should one be able to append labels `1:10` with labels `1:5`? It probably makes sense to require concatenated dimensional axes to still be monotonically increasing. But what about appending `1:10` and `21:30`? Still disallow? Or replace the axis' `val` with a 20-element vector (not type-stable)?

**Comment by mbauman** [comment]
We already error on indexing and other constructions that'd create an AxisArray with an un-sorted dimensional axis, so erroring for un-ordered axes here makes sense.

For discontinuities and changing step sizes, I think I'd either always error or always use a [PiecewiseIncreasingRange](https://github.com/simonster/PiecewiseIncreasingRanges.jl). I don't do much concatenation that extends axes like this in my own work, so I don't have a good sense if the extra flexibility is worth the performance tradeoff.
