### ISSUE TITLE
Preserve omitted dimensions when indexing by axis values?

### ISSUE THREAD

**Issue by mbauman** [mbauman/AxisArrays.jl#4]
I'm really liking how the API is coming together.  Normal indexing works like a charm, and it makes a lot of sense that the special `A[Axis{:time}(idxs)]` indexing form would preserve all the other (unnamed) dimensions.  But what about when you index by axis values with missing trailing dimensions?  A good example here would be the following:

```julia
A = AxisArray(reshape(1:15, 5,3), (.1:.1:0.5, [:a, :b, :c]))
A[Interval(.22, .44)]
```

As it is currently designed, this will lower to a call to `A.data[3:4]`, which is linearly indexing across both dimensions.  As such, you'll only get back two elements, when you probably wanted those two rows from all three columns (`A.data[3:4, :]`).

I think there's a case to be made here to preserve the omitted dimensions.  Since we're indexing by axis value, we *cannot* select any indices that are out-of-bounds for that dimension — we'll only ever get values from the first column.  That doesn't seem very useful to me.  Any objections?

**Comment by tshort** [comment]
+1
